server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

product:
  ribbon:
    listOfServers: localhost:8082, localhost:7777
    maxAutoRetries: 0
    maxAutoRetriesNextServer: 1
