server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
